<?xml version="1.0"?>
<!DOCTYPE document [
	<!ELEMENT document (section+)> 
		<!ELEMENT section (heading|section|bibentry)*>
		<!ATTLIST section level (1|2|3|4|5) #REQUIRED>
		<!ATTLIST section id CDATA #REQUIRED>
			<!ELEMENT heading (#PCDATA|boldtitle|title|subtitle)*>
				<!ELEMENT title (#PCDATA)> 
				<!ELEMENT boldtitle (#PCDATA)> 
				<!ELEMENT subtitle (#PCDATA)> 
			<!ELEMENT bibentry (#PCDATA)>
			<!ATTLIST bibentry id CDATA #REQUIRED>
		<!ENTITY rsquo "’">
]>

<document> 
	<section level="1" id="1"> 
		<section level="2" id="1"> 
			<heading><boldtitle>Step 1:</boldtitle><subtitle> Consult bibliographies of bibliographies and guides to research methods to identify existing bibliographies of primary or secondary works associated with an author or topic. </subtitle></heading> 
			<section level="3" id="1"> 
				<heading><title>General Bibliographies of Bibliographies and Guides to Research Methods</title></heading>
				<bibentry id="M1357">Bracken</bibentry> 
				<bibentry id="D170">Weiner</bibentry> 
				<bibentry id="D145"></bibentry>
				<bibentry id="G325">Wortman</bibentry> 
				<bibentry id="G327">Balay</bibentry> 
				<bibentry id="D155">Besterman</bibentry> 
			</section>
			<section level="3" id="2">
				<heading><title>Specialized Bibliographies of Bibliographies and Guides to Research Methods</title></heading>
				<section level="4" id="1">
					<heading><title>American Literature</title></heading> 
					<bibentry id="M1357">Bracken</bibentry> 
					<bibentry id="Q3715"></bibentry>
					<bibentry id="Q3995">Courtney</bibentry> 
					<bibentry id="Q4100">Stein</bibentry> 
					<bibentry id="Q4210">Matuozzi and Lindsay</bibentry> 
					<bibentry id="Q4265">McPheron</bibentry> 
					<bibentry id="Q4315">McPheron</bibentry> 
				</section> 
				<section level="4" id="2">
					<heading><title>Australian Literature</title></heading> 
					<bibentry id="R4435">Christenberry and Courtney</bibentry> 
				</section> 
				<section level="4" id="3">
					<heading><title>Canadian Literature</title></heading> 
					<bibentry id="R4585"></bibentry>
				</section> 
				<section level="4" id="4">
					<heading><title>Caribbean-Area Literatures</title></heading> 
					<bibentry id="R4785">Jordan</bibentry> 
				</section> 
				<section level="4" id="5">
					<heading><title>Children’s Literature</title></heading> 
					<bibentry id="U5435">Grenby and Reynolds</bibentry> 
				</section> 
				<section level="4" id="6">
					<heading><title>English Literature</title></heading> 
					<bibentry id="M1355">Howard-Hill</bibentry> 
					<bibentry id="M1357">Bracken</bibentry> 
					<bibentry id="M1960">Bowers and Keeran</bibentry> 
					<bibentry id="M2220">Lund</bibentry> 
					<bibentry id="M2447">Van Vuuren</bibentry> 
					<bibentry id="M2745">Lewis</bibentry> 
					<bibentry id="M2760">Mellown</bibentry> 
				</section> 
				<section level="4" id="7">
					<heading><title>Festschriften</title></heading> 
					<bibentry id="D165"></bibentry>
				</section> 
				<section level="4" id="8">
					<heading><title>Fiction</title></heading> 
					<bibentry id="L833"></bibentry>
					<bibentry id="Q4265">McPheron</bibentry> 
				</section> 
				<section level="4" id="9">
					<heading><title>Film</title></heading> 
					<bibentry id="U5755"></bibentry>
				</section> 
				<section level="4" id="10">
					<heading><title>Irish Literature</title></heading> 
					<bibentry id="N2905">Gre</bibentry>
					<bibentry id="N2930">Eager</bibentry> 
				</section> 
				<section level="4" id="11">
					<heading><title>Medieval Studies</title></heading> 
					<bibentry id="M1805">Rouse</bibentry> 
				</section> 
				<section level="4" id="12">
					<heading><title>New Zealand Literature</title></heading> 
					<bibentry id="R4435">Christenberry and Courtney</bibentry> 
				</section> 
				<section level="4" id="13">
					<heading><title>Periodicals</title></heading> 
					<bibentry id="K610"></bibentry>
				</section> 
				<section level="4" id="14">
					<heading><title>Poetry</title></heading> 
					<bibentry id="Q4315">McPheron</bibentry> 
				</section> 
				<section level="4" id="15">
					<heading><title>Religion and Literature</title></heading> 
					<bibentry id="U6325"></bibentry>
				</section> 
				<section level="4" id="16">
					<heading><title>Women&rsquo;s Studies</title></heading> 
					<bibentry id="E220">Nelson</bibentry> 
					<bibentry id="U6585"></bibentry>
				</section> 
			</section> <!--end level 3--> 
		</section> <!--end step 1--> 

		<section level="2" id="2"> 
			<heading><boldtitle>Step 2:</boldtitle><subtitle> Search catalogs of libraries.</subtitle></heading> 
			<section level="3" id="1"> 
				<heading><title>a. Locate major library collections.</title></heading>
				<section level="4" id="1">
					<heading><title>General Guides</title></heading> 
					<bibentry id="E205">Ash and Miller</bibentry> 
					<bibentry id="E210"></bibentry>
				</section> 
				<section level="4" id="2">
					<heading><title>Other Guides to Collections</title></heading> 
					<bibentry id="N2935">Lester</bibentry> 
					<bibentry id="Q3730"></bibentry>
					<bibentry id="U5460"></bibentry>
					<bibentry id="U6290"></bibentry>
				</section> 
				<section level="3" id="3"> 
					<heading><title>b. Search union catalogs.</title></heading> 
					<bibentry id="E225"></bibentry>
					<bibentry id="E235"></bibentry>
				</section> 
				<section level="3" id="4"> 
					<heading><title>c. Search catalogs of major national libraries.</title></heading> 
					<bibentry id="E250"></bibentry>
					<bibentry id="E255"></bibentry>
					<bibentry id="E260"></bibentry>
				</section> 
			</section><!--end of level 3--> 
		</section> <!--end of step 2--> 
		<section level="2" id="3"> 
			<heading><boldtitle>Step 3:</boldtitle><subtitle> Search national bibliographies.</subtitle></heading> 
			<section level="3" id="1"> 
				<heading><title>General Guides</title></heading> 
				<bibentry id="D180">Domay</bibentry> 
				<heading><title>American Literature</title></heading>
				<bibentry id="Q4005"></bibentry>
				<bibentry id="Q4010"></bibentry>
				<bibentry id="M1377"></bibentry>
				<bibentry id="M1990"></bibentry>
				<bibentry id="M1995"></bibentry>
				<bibentry id="M2470"></bibentry>
				<bibentry id="M2475"></bibentry>
				<bibentry id="Q4125"></bibentry>
				<bibentry id="Q4130"></bibentry>
				<bibentry id="Q4120"></bibentry>
				<bibentry id="Q4110"></bibentry>
			</section> 
			<section level="3" id="2"> 
				<heading><title>Australian Literature</title></heading>
				<bibentry id="R4463"></bibentry>
				<bibentry id="R4465"></bibentry>
				<bibentry id="R4470">Ferguson</bibentry> 
			</section> 
			<section level="3" id="3"> 
				<heading><title>Canadian Literature</title></heading>
				<bibentry id="R4595"></bibentry>
				<bibentry id="R4615">Tremaine</bibentry> 
			</section> 
			<section level="3" id="4"> 
				<heading><title>English Literature</title></heading>
				<bibentry id="M1377"></bibentry>
				<bibentry id="M1820"></bibentry>
				<bibentry id="M1990"></bibentry>
				<bibentry id="M1995"></bibentry>
				<bibentry id="M2470"></bibentry>
				<bibentry id="M2475"></bibentry>
				<bibentry id="M2770"></bibentry>
			</section> 
			<section level="3" id="5"> 
				<heading><title>New Zealand Literature</title></heading>
				<bibentry id="R4810">Bagnall</bibentry> 
				<bibentry id="R4815"></bibentry>
			</section> 
		</section> <!--end of step 3--> 
		<section level="2" id="4"> 
			<heading><boldtitle>Step 4:</boldtitle><subtitle> Consult specialized guides devoted to primary works related to a national literature, genre, or topic.</subtitle></heading> 
			<section level="3" id="1"> 
				<heading><title>American Literature</title></heading>
				<bibentry id="J595"></bibentry>
				<bibentry id="L1060"></bibentry>
				<bibentry id="M2640">Grimes</bibentry> 
				<bibentry id="Q3250">Blanck</bibentry> 
				<bibentry id="Q3255"></bibentry>
				<bibentry id="Q3405"></bibentry>
				<bibentry id="Q3410">Chielens</bibentry> 
				<bibentry id="Q3473">Davis and Joyce</bibentry> 
				<bibentry id="Q3512"></bibentry>
				<bibentry id="Q3534">Davis and Joyce</bibentry> 
				<bibentry id="Q3540">Arksey</bibentry> 
				<bibentry id="Q3545"></bibentry>
				<bibentry id="Q3720"></bibentry>
				<bibentry id="Q3723"></bibentry>
				<bibentry id="Q3725"></bibentry>
				<bibentry id="Q3730"></bibentry>
				<bibentry id="Q3775"></bibentry>
				<bibentry id="Q3815">Margolies</bibentry> 
				<bibentry id="Q3825">Hatch and Abdullah</bibentry> 
				<bibentry id="Q3840"></bibentry>
				<bibentry id="Q3835">Wagner</bibentry> 
				<bibentry id="Q3840"></bibentry>
				<bibentry id="Q3845">French</bibentry> 
				<bibentry id="Q3850">Brignano</bibentry> 
				<bibentry id="Q3870">Littlefield</bibentry> 
				<bibentry id="Q3920">Colonnese</bibentry> 
				<bibentry id="Q3925">Brumble</bibentry> 
				<bibentry id="Q3940">Cheung</bibentry> 
				<bibentry id="Q3990">Nadel</bibentry> 
				<bibentry id="Q4000"></bibentry>
				<bibentry id="Q4015"></bibentry>
				<bibentry id="Q4035">Brigham</bibentry> 
				<bibentry id="Q4040">Kribbs</bibentry> 
				<bibentry id="Q4045"></bibentry>
				<bibentry id="Q4060">Pitcher</bibentry> 
				<bibentry id="Q4070">Hill</bibentry> 
				<bibentry id="Q4075"></bibentry>
				<bibentry id="Q4080">Lemay</bibentry> 
				<bibentry id="Q4085">Wegelin</bibentry> 
				<bibentry id="Q4115"></bibentry>
				<bibentry id="Q4180">Wright</bibentry> 
				<bibentry id="Q4195"></bibentry>
				<bibentry id="Q4225"></bibentry>
				<bibentry id="Q4230">Lepper</bibentry> 
				<bibentry id="Q4235">Vrana</bibentry> 
				<bibentry id="Q4267"></bibentry>
				<bibentry id="Q4285">Leiter</bibentry> 
				<bibentry id="Q4320">Davis</bibentry> 
				<bibentry id="Q4325"></bibentry>
				<bibentry id="Q4330">Reardon</bibentry> 
				<bibentry id="Q4345">Brier</bibentry> 
				<bibentry id="U5160">Huddleston</bibentry> 
				<bibentry id="U5473"></bibentry>
				<bibentry id="U5475"></bibentry>
			</section> 
			<section level="3" id="2"> 
				<heading><title>Australian Literature</title></heading>
				<bibentry id="L1060"></bibentry>
				<bibentry id="R4463"></bibentry>
				<bibentry id="R4465"></bibentry>
				<bibentry id="R4470">Ferguson</bibentry> 
				<bibentry id="R4475">Miller</bibentry> 
				<bibentry id="R4488">Ross</bibentry> 
				<bibentry id="R4500">Stuart</bibentry> 
				<bibentry id="R4525">Torre</bibentry> 
				<bibentry id="R4530">Day</bibentry> 
				<bibentry id="R4545">Webby</bibentry> 
			</section> 
			<section level="3" id="3"> 
				<heading><title>Canadian Literature</title></heading>
				<bibentry id="L1060"></bibentry>
				<bibentry id="Q3990">Nadel</bibentry> 
				<bibentry id="Q4010"></bibentry>
				<bibentry id="Q4325"></bibentry>
				<bibentry id="R4595"></bibentry>
				<bibentry id="R4605"></bibentry>
				<bibentry id="R4610"></bibentry>
				<bibentry id="R4613">Miska</bibentry> 
				<bibentry id="R4615">Tremaine</bibentry> 
				<bibentry id="R4620">Watters</bibentry> 
				<bibentry id="R4703">Weiss</bibentry> 
				<bibentry id="R4705">Hayne</bibentry> 
				<bibentry id="R4710">Hoy</bibentry> 
				<bibentry id="R4720">Rinfret</bibentry> 
				<bibentry id="R4722"></bibentry>
				<bibentry id="R4725"></bibentry>
				<bibentry id="R4750">McQuarrie, Mercer, and Ripley</bibentry> 
			</section> 
			<section level="3" id="4"> 
				<heading><title>Children&rsquo;s Literature</title></heading>
				<bibentry id="Q3940">Cheung</bibentry> 
				<bibentry id="U5460"></bibentry>
				<bibentry id="U5470"></bibentry>
				<bibentry id="U5473"></bibentry>
				<bibentry id="U5475"></bibentry>
				<bibentry id="U5540"></bibentry>
			</section> 
			<section level="3" id="5"> 
				<heading><title>Drama and Theater</title></heading>
				<bibentry id="L1150">Montgomery</bibentry> 
				<bibentry id="L1155"></bibentry>
				<bibentry id="M1540"></bibentry>
				<bibentry id="M1545">Nicoll</bibentry> 
				<bibentry id="M1550">Stratman</bibentry> 
				<bibentry id="M2135">Greg</bibentry> 
				<bibentry id="M2136">Wiggins</bibentry> 
				<bibentry id="M2137">Farmer and Lesser</bibentry> 
				<bibentry id="M2377">Burling</bibentry> 
				<bibentry id="Q3512"></bibentry>
				<bibentry id="Q3825"></bibentry>
				<bibentry id="Q3845">French</bibentry> 
				<bibentry id="Q4070">Hill</bibentry> 
				<bibentry id="Q4195"></bibentry>
				<bibentry id="R4720">Rinfret</bibentry> 
				<bibentry id="R4725"></bibentry>
			</section> <!-- end of level 3--> 
			<section level="3" id="6"> 
				<heading><title>English Literature</title></heading>
				<bibentry id="L1060"></bibentry>
				<bibentry id="M1370">Mullins</bibentry> 
				<bibentry id="M1376"></bibentry>
				<bibentry id="M1377"></bibentry>
				<bibentry id="M1385"></bibentry>
				<bibentry id="M1540"></bibentry>
				<bibentry id="M1545">Nicoll</bibentry> 
				<bibentry id="M1550">Stratman</bibentry> 
				<bibentry id="M1610">Matthews</bibentry> 
				<bibentry id="M1615">Matthews</bibentry> 
				<bibentry id="M1820"></bibentry>
				<bibentry id="M1825">Severs, Hartung, and Beidler</bibentry> 
				<bibentry id="M1927">Grantley</bibentry> 
				<bibentry id="M1945"></bibentry>
				<bibentry id="M1990"></bibentry>
				<bibentry id="M1995"></bibentry>
				<bibentry id="M2007">Smith and Cardinale</bibentry> 
				<bibentry id="M2095">Mish</bibentry> 
				<bibentry id="M2100">O&rsquo;Dell</bibentry> 
				<bibentry id="M2135">Greg</bibentry> 
				<bibentry id="M2136">Wiggins</bibentry> 
				<bibentry id="M2180">Case</bibentry> 
				<bibentry id="M2185">Frank</bibentry> 
				<bibentry id="M2190">Ringler</bibentry> 
				<bibentry id="M2235"></bibentry>
				<bibentry id="M2270">Crane</bibentry> 
				<bibentry id="M2320">Beasley</bibentry> 
				<bibentry id="M2325">McBurney</bibentry> 
				<bibentry id="M2330">Mayo</bibentry> 
				<bibentry id="M2335">Raven</bibentry> 
				<bibentry id="M2336"></bibentry>
				<bibentry id="M2377">Burling</bibentry> 
				<bibentry id="M2415">Foxon</bibentry> 
				<bibentry id="M2420">Jackson</bibentry> 
				<bibentry id="M2435">Stauffer</bibentry> 
				<bibentry id="M2466"></bibentry>
				<bibentry id="M2467"></bibentry>
				<bibentry id="M2470"></bibentry>
				<bibentry id="M2475"></bibentry>
				<bibentry id="M2530"></bibentry>
				<bibentry id="M2535"></bibentry>
				<bibentry id="M2540"></bibentry>
				<bibentry id="M2545"></bibentry>
				<bibentry id="M2550">Ward</bibentry> 
				<bibentry id="M2635">Sadleir</bibentry> 
				<bibentry id="M2640">Grimes</bibentry> 
				<bibentry id="M2645">Harris</bibentry> 
				<bibentry id="M2650">Snell</bibentry> 
				<bibentry id="M2655">Vann</bibentry> 
				<bibentry id="M2660">Wolff</bibentry> 
				<bibentry id="M2707">Reilly</bibentry> 
				<bibentry id="M2770"></bibentry>
				<bibentry id="M2775"></bibentry>
				<bibentry id="M2840">Rice</bibentry> 
				<bibentry id="Q3512"></bibentry>
				<bibentry id="Q3534">Davis and Joyce</bibentry> 
				<bibentry id="Q4290">Harris</bibentry> 
			</section> 
			<section level="3" id="7"> 
				<heading><title>Fiction</title></heading>
				<bibentry id="L835"></bibentry>
				<bibentry id="L860">Bleiler</bibentry> 
				<bibentry id="L885">Baker</bibentry> 
				<bibentry id="L890">Adamson</bibentry> 
				<bibentry id="L895">Adamson</bibentry> 
				<bibentry id="L900">Nield</bibentry> 
				<bibentry id="L910">Stephensen-Payne, Contento, and Miller</bibentry> 
				<bibentry id="L915">Hubin</bibentry> 
				<bibentry id="L950">Laurenti</bibentry> 
				<bibentry id="L980"></bibentry>
				<bibentry id="L985">Contento</bibentry> 
				<bibentry id="L987">Miller</bibentry> 
				<bibentry id="L990">Reginald</bibentry> 
				<bibentry id="L995">Schlobin</bibentry> 
				<bibentry id="L1000">Tuck</bibentry> 
				<bibentry id="L1015">Barron</bibentry> 
				<bibentry id="L1055">Sargent</bibentry> 
				<bibentry id="L1060"></bibentry>
				<bibentry id="L1085"></bibentry>
				<bibentry id="M2095">Mish</bibentry> 
				<bibentry id="M2100">O&rsquo;Dell</bibentry> 
				<bibentry id="M2320">Beasley</bibentry> 
				<bibentry id="M2325">McBurney</bibentry> 
				<bibentry id="M2330">Mayo</bibentry> 
				<bibentry id="M2335">Raven</bibentry> 
				<bibentry id="M2336"></bibentry>
				<bibentry id="M2635">Sadleir</bibentry> 
				<bibentry id="M2640">Grimes</bibentry> 
				<bibentry id="M2645">Harris</bibentry> 
				<bibentry id="M2650">Snell</bibentry> 
				<bibentry id="M2655">Vann</bibentry> 
				<bibentry id="M2660"></bibentry>
				<bibentry id="M2840">Rice</bibentry> 
				<bibentry id="N3025">Brown</bibentry> 
				<bibentry id="Q3473"></bibentry>
				<bibentry id="Q3815">Margolies</bibentry> 
				<bibentry id="Q3920">Colonnese</bibentry> 
				<bibentry id="Q4060">Pitcher</bibentry> 
				<bibentry id="Q4180">Wright</bibentry> 
				<bibentry id="Q4267"></bibentry>
				<bibentry id="R4525">Torre</bibentry> 
				<bibentry id="R4530">Day</bibentry> 
				<bibentry id="R4703">Weiss</bibentry> 
				<bibentry id="R4705">Hayne</bibentry> 
				<bibentry id="R4710">Hoy</bibentry> 
				<bibentry id="R4835">Burns</bibentry>
			</section>
			<section level="3" id="8"> 
				<heading><title>Gay, Lesbian, Bisexual, and Transgendered Literature</title></heading>
				<bibentry id="U5930">Bosman and Bradford</bibentry> 
			</section> 
			<section level="3" id="9"> 
				<heading><title>Gothic Fiction</title></heading>
				<bibentry id="L860">Bleiler</bibentry> 
			</section> 
			<section level="3" id="10"> 
				<heading><title>Historical Fiction</title></heading>
				<bibentry id="L885">Baker</bibentry> 
				<bibentry id="L890">Adamson</bibentry> 
				<bibentry id="L895">Adamson</bibentry> 
				<bibentry id="L900">Nield</bibentry> 
			</section> 
			<section level="3" id="11"> 
				<heading><title>Irish Literature</title></heading>
				<bibentry id="N2935">Lester</bibentry> 
				<bibentry id="N2945"></bibentry>
				<bibentry id="N2985">McKenna</bibentry> 
				<bibentry id="N3000"></bibentry>
				<bibentry id="N3025">Brown</bibentry> 
			</section> 
			<section level="3" id="12"> 
				<heading><title>Little Magazines</title></heading>
				<bibentry id="K770">Hoffman</bibentry> 
				<bibentry id="K775"></bibentry>
				<bibentry id="K780"></bibentry>
				<bibentry id="K785">Bloomfield</bibentry> 
				<bibentry id="K790"></bibentry>
				<bibentry id="K793"></bibentry> 
				<bibentry id="K795"></bibentry>
				<bibentry id="K800"></bibentry>
			</section> 
			<section level="3" id="13"> 
				<heading><title>Mystery Fiction</title></heading>
				<bibentry id="L910">Stephensen-Payne, Contento, and Miller</bibentry> 
				<bibentry id="L915">Hubin</bibentry> 
			</section> 
			<section level="3" id="14"> 
				<heading><title>New Zealand Literature</title></heading>
				<bibentry id="L1060"></bibentry>
				<bibentry id="R4810">Bagnall</bibentry> 
				<bibentry id="R4815"></bibentry>
				<bibentry id="R4820">Thomson</bibentry> 
				<bibentry id="R4835">Burns</bibentry> 
			</section> 
			<section level="3" id="15"> 
				<heading><title>Poetry</title></heading>
				<bibentry id="L1235"></bibentry>
				<bibentry id="M1940">Boffey</bibentry> 
				<bibentry id="M2180">Case</bibentry> 
				<bibentry id="M2185">Frank</bibentry> 
				<bibentry id="M2190">Ringler</bibentry> 
				<bibentry id="M2415">Foxon</bibentry> 
				<bibentry id="M2420">Jackson</bibentry> 
				<bibentry id="M2707">Reilly</bibentry> 
				<bibentry id="Q3534">Davis and Joyce</bibentry> 
				<bibentry id="Q3840"></bibentry>
				<bibentry id="Q3845">French</bibentry> 
				<bibentry id="Q4075"></bibentry>
				<bibentry id="Q4080">Lemay</bibentry> 
				<bibentry id="Q4090">Scheick</bibentry> 
				<bibentry id="Q4095">Yannella</bibentry> 
				<bibentry id="Q4105"></bibentry>
				<bibentry id="Q4110"></bibentry>
				<bibentry id="Q4320">Davis</bibentry> 
				<bibentry id="Q4325"></bibentry>
				<bibentry id="Q4330">Reardon</bibentry> 
				<bibentry id="R4545">Webby</bibentry> 
				<bibentry id="R4750"></bibentry>
				<bibentry id="U5160">Huddleston</bibentry> 
				<bibentry id="U5540"></bibentry>
			</section> 
			<section level="3" id="16"> 
				<heading><title>Prose</title></heading>
				<bibentry id="M1945"></bibentry>
				<bibentry id="Q4095">Yannella</bibentry> 
				<bibentry id="Q4345">Brier</bibentry> 
				<bibentry id="R4530">Day</bibentry> 
				<bibentry id="R4710">Hoy</bibentry> 
			</section> 
			<section level="3" id="17"> 
				<heading><title>Science Fiction</title></heading>
				<bibentry id="L980"></bibentry>
				<bibentry id="L985">Contento</bibentry> 
				<bibentry id="L987">Miller</bibentry> 
				<bibentry id="L990">Reginald</bibentry> 
				<bibentry id="L995">Schlobin</bibentry> 
				<bibentry id="L1000">Tuck</bibentry> 
				<bibentry id="L1015">Barron</bibentry> 
			</section> 
			<section level="3" id="18"> 
				<heading><title>Scottish Literature</title></heading>
				<bibentry id="O3103"></bibentry>
			</section> 
			<section level="3" id="19"> 
				<heading><title>Short Fiction</title></heading>
				<bibentry id="G385"></bibentry>
				<bibentry id="G400"></bibentry>
				<bibentry id="L1085"></bibentry>
				<bibentry id="M2645">Harris</bibentry> 
				<bibentry id="R4525">Torre</bibentry> 
				<bibentry id="R4703">Weiss</bibentry> 
			</section> 
			<section level="3" id="20"> 
				<heading><title>Welsh Literature</title></heading>
				<bibentry id="P3150">Jones</bibentry> 
				<bibentry id="P3165">Walters</bibentry> 
			</section> 
		</section> <!--end of step 4--> 
		<section level="2" id="5"> 
			<heading><boldtitle>Step 5:</boldtitle><subtitle> Search text archives.</subtitle></heading> 
			<section level="3" id="1"> 
				<heading><title>American Literature</title></heading>
				<bibentry id="I527"></bibentry>
				<bibentry id="Q3514"></bibentry>
				<bibentry id="Q3536"></bibentry>
				<bibentry id="Q3540"></bibentry>
				<bibentry id="Q3848"></bibentry>
				<bibentry id="Q4005"></bibentry>
				<bibentry id="Q4015"></bibentry>
				<bibentry id="Q4050"></bibentry>
				<bibentry id="Q4125"></bibentry>
				<bibentry id="Q4130"></bibentry>
				<bibentry id="Q4180"></bibentry>
				<bibentry id="Q4183"></bibentry>
				<bibentry id="Q4333"></bibentry>
			</section> 
			<section level="3" id="2"> 
				<heading><title>Broadsides</title></heading>
				<bibentry id="Q4130"></bibentry>
				<bibentry id="Q4130"></bibentry>
			</section> 
			<section level="3" id="3"> 
				<heading><title>Canadian Literature</title></heading>
				<bibentry id="R4753"></bibentry>
			</section> 
			<section level="3" id="4"> 
				<heading><title>Diaries</title></heading>
				<bibentry id="M1615"></bibentry>
				<bibentry id="Q3540"></bibentry>
			</section> 
			<section level="3" id="5"> 
				<heading><title>Drama</title></heading>
				<bibentry id="L1158"></bibentry>
				<bibentry id="M1553"></bibentry>
				<bibentry id="Q3514"></bibentry>
			</section> 
			<section level="3" id="6"> 
				<heading><title>English Literature</title></heading>
				<bibentry id="I527"></bibentry>
				<bibentry id="M1553"></bibentry>
				<bibentry id="M1593"></bibentry>
				<bibentry id="M1615"></bibentry>
				<bibentry id="M1705"></bibentry>
				<bibentry id="M2009"></bibentry>
				<bibentry id="M2103"></bibentry>
				<bibentry id="M2238"></bibentry>
				<bibentry id="M2339"></bibentry>
				<bibentry id="M2663"></bibentry>
				<bibentry id="M2894"></bibentry>
			</section> 
			<section level="3" id="7"> 
				<heading><title>Fiction</title></heading>
				<bibentry id="M2103"></bibentry>
				<bibentry id="M2339"></bibentry>
				<bibentry id="M2663"></bibentry>
				<bibentry id="Q4180"></bibentry>
				<bibentry id="Q4183"></bibentry>
			</section> 
			<section level="3" id="8"> 
				<heading><title>Poetry</title></heading>
				<bibentry id="M1593"></bibentry>
				<bibentry id="M2894"></bibentry>
				<bibentry id="Q3536"></bibentry>
				<bibentry id="Q3848"></bibentry>
				<bibentry id="Q4333"></bibentry>
				<bibentry id="R4753"></bibentry>
			</section> 
		</section> <!--end of step 5--> 
	</section> <!-- end of Page 1--> 

	<section level="1" id="2"> <!-- start of Page 2 -->  
		<section level="2" id="1"> 
			<heading><boldtitle>Step 1:</boldtitle><subtitle> Consult guides to archives and collections.</subtitle></heading> 
			<bibentry id="F280"></bibentry>
			<bibentry id="F283">Foster and Sheppard</bibentry> 
			<bibentry id="F285"></bibentry>
			<bibentry id="F290"></bibentry>
			<bibentry id="F293"></bibentry>
			<bibentry id="M2860">Innes</bibentry> 
			<bibentry id="Q3245"></bibentry>
			<bibentry id="R4462"></bibentry>
			<bibentry id="U5465">Fraser</bibentry> 
		</section> <!--end of Page 2, Step 1--> 

		<section level="2" id="2"> 
			<heading><boldtitle>Step 2:</boldtitle><subtitle> Search union catalogs.</subtitle></heading> 
			<bibentry id="E225"></bibentry>
			<bibentry id="F295"></bibentry>
			<bibentry id="R4590"></bibentry>
			<bibentry id="R4722"></bibentry>
			<bibentry id="R4808"></bibentry>
		</section> <!-- end of Page 2, Step 2--> 
		<section level="2" id="3"> 
			<heading><boldtitle>Step 3:</boldtitle><subtitle> Search catalogs of major institutional collections.</subtitle></heading> 
			<bibentry id="F300"></bibentry>
			<bibentry id="F300"></bibentry>
			<bibentry id="F300"></bibentry>
			<bibentry id="F300"></bibentry>
		</section> <!-- end of Page 2, Step 3 --> 
		<section level="2" id="4"> 
			<heading><boldtitle>Step 4:</boldtitle><subtitle> Search catalogs devoted to a national literature, geographical area, or subject.</subtitle></heading> 
			<bibentry id="F305">Schoenberg</bibentry> 
			<bibentry id="M1365"></bibentry>
			<bibentry id="M1540"></bibentry>
			<bibentry id="M1590">Crum</bibentry> 
			<bibentry id="M1645">Ker</bibentry> 
			<bibentry id="M1810">Ker</bibentry> 
			<bibentry id="M1815">Ricci</bibentry> 
			<bibentry id="M1940">Boffey</bibentry> 
			<bibentry id="M1945"></bibentry>
			<bibentry id="M2227"></bibentry>
			<bibentry id="M2765"></bibentry>
			<bibentry id="N2940">Hayes</bibentry> 
			<bibentry id="Q3230"></bibentry>
			<bibentry id="Q3235"></bibentry>
			<bibentry id="Q3240"></bibentry>
		</section> <!-- end of Page 2, Step 4 --> 
		<section level="2" id="5"> 
			<heading><boldtitle>Step 5:</boldtitle><subtitle> Search text archives.</subtitle></heading> 
			<bibentry id="M1373"></bibentry>
		</section> <!-- end of Page 2, Step 5 --> 
	</section> <!-- end of Page 2 --> 

	<section level="1" id="3"> <!-- start of Page 3 -->  
		<section level="2" id="1"> 
			<heading><boldtitle>Step 1:</boldtitle><subtitle> Consult bibliographies of bibliographies to identify existing bibliographies of secondary works associated with an author or topic.</subtitle></heading> 
			<section level="3" id="1"> 
				<heading><title>General Bibliographies of Bibliographies </title></heading>
				<bibentry id="M1357">Bracken</bibentry> 
				<bibentry id="D170">Weiner</bibentry> 
				<bibentry id="D145"></bibentry>
				<bibentry id="G325">Wortman</bibentry> 
			</section>
			<section level="3" id="2"> 
				<heading><title>Specialized Bibliographies of Bibliographies</title></heading>
				<section level="4" id="1">
					<heading><title>American Literature</title></heading> 
					<bibentry id="M1357">Bracken</bibentry> 
					<bibentry id="Q3715"></bibentry>
					<bibentry id="Q4265">McPheron</bibentry> 
					<bibentry id="Q4315">McPheron</bibentry> 
				</section> 
				<section level="4" id="2">
					<heading><title>Book Review Indexes</title></heading> 
					<bibentry id="G410">Gray</bibentry> 
				</section> 
				<section level="4" id="3">
					<heading><title>Canadian Literature</title></heading> 
					<bibentry id="R4585">Ingles</bibentry> 
				</section> 
				<section level="4" id="4">
					<heading><title>Caribbean-Area Literatures</title></heading> 
					<bibentry id="R4785">Jordan</bibentry> 
				</section> 
				<section level="4" id="5">
					<heading><title>Dictionaries</title></heading> 
					<bibentry id="U6018">Cop</bibentry> 
				</section> 
				<section level="4" id="6">
					<heading><title>Dissertations and Theses</title></heading> 
					<bibentry id="H455">Reynolds</bibentry> 
				</section> 
				<section level="4" id="7">
					<heading><title>English Literature</title></heading> 
					<bibentry id="M1355">Howard-Hill</bibentry> 
					<bibentry id="M1357">Bracken</bibentry> 
					<bibentry id="M2220">Lund</bibentry> 
					<bibentry id="M2760">Mellown</bibentry> 
				</section> 
				<section level="4" id="8">
					<heading><title>Festschriften</title></heading> 
					<bibentry id="D165"></bibentry>
				</section> 
				<section level="4" id="9">
					<heading><title>Fiction</title></heading> 
					<bibentry id="L833">Hartman and Drost</bibentry> 
					<bibentry id="Q4265">McPheron</bibentry> 
				</section> 
				<section level="4" id="10">
					<heading><title>Film</title></heading> 
					<bibentry id="U5755">Wulff</bibentry> 
				</section> 
				<section level="4" id="11">
					<heading><title>History</title></heading> 
					<bibentry id="U6490">Henige</bibentry> 
				</section> 
				<section level="4" id="12">
					<heading><title>Irish Literature</title></heading> 
					<bibentry id="N2930">Eager</bibentry> 
				</section> 
				<section level="4" id="13">
					<heading><title>Library Catalogs</title></heading> 